name: ThePitUltimate
version: 4.5.0
description: A modern thepit minigame plugin.
authors: [ YeyingXingchen, KleeLoveLife, Rabbit0w0, Araykal ]

api-version: 1.8
main: cn.charlotte.pit.ThePit
load: POSTWORLD
depend: [ LuckPerms, ProtocolLib ]
softdepend: [ PlayerPoints, WorldEdit, FastAsyncWorldEdit ]